apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  labels:
    app: nginx
  name: nginx
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.99.6
  selector:
    app: nginx
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 80
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443
    nodePort: 443
  - name: ssh
    protocol: TCP
    port: 22
    targetPort: 22
    nodePort: 22
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          imagePullPolicy: Never
          ports:
          - containerPort: 80
            name: http
          - containerPort: 443
            name: https
          - containerPort: 22
            name: ssh